CREATE USER "klage-user" WITH PASSWORD 'klage-user';
CREATE USER "klage-admin" WITH PASSWORD 'klage-admin';
GRANT ALL PRIVILEGES ON DATABASE klage TO "klage-user";
GRANT ALL PRIVILEGES ON DATABASE klage TO "klage-admin";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "klage-user";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "klage-user";