apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: privat-klage-mottatt-v1
  namespace: klage
  labels:
    team: klage
spec:
  pool: {{pool}}
  config:
  {{#each config as |value key|}}
     {{key}}: {{value}}
  {{/each}}
  acl:
    - team: klage
      application: klage-dittnav-api
      access: write
    - team: klage
      application: klage-arkiver-journalpost
      access: read
    - team: klage
      application: klage-kafka-manager
      access: read