apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: klage-dittnav-api
  namespace: klage
  labels:
    team: klage
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "7200"
spec:
  image: {{ image }}
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
  kafka:
    pool: {{kafka_pool}}
  port: 7070
  liveness:
    path: /internal/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 2048Mi
  replicas:
    min: 2
    max: {{max_replicas}}
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /internal/prometheus
  gcp:
    sqlInstances:
      - tier: {{db_tier}}
        diskAutoresize: true
        highAvailability: {{db_high_availability}}
        type: {{db_type}}
        databases:
          - name: klage
            envVarPrefix: DB
  webproxy: true
  tokenx:
    enabled: true
  {{#if ingresses}}
  ingresses:
  {{#each ingresses as |ingress|}}
    - {{ingress}}
  {{/each}}
  {{/if}}
  accessPolicy:
    inbound:
      rules:
        - application: klage-dittnav
        - application: klage-arkiver-journalpost
    outbound:
      external:
        {{#each externalHosts as |host|}}
        - host: {{host}}
        {{/each}}
        - host: login.microsoftonline.com
        - host: hooks.slack.com
      rules:
        - application: klage-file-api
        - application: klage-dittnav-pdfgen
        - application: clamav
          namespace: nais-system
        - application: logging
          namespace: nais-system
  envFrom:
    - secret: srvklage-dittnav
    - secret: sts-apikey
    - secret: pdl-apikey
    - secret: slack-url
    - secret: slack-channel-id
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{springProfile}}
  {{#each envs}}
    - name: {{name}}
      value: {{value}}
  {{/each}}