name: Deploy (dev -> e2e -> prod)

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'kafka-aiven/**'
      - '.github/dependabot.yml'

jobs:
  deploy_to_dev:
    permissions:
      contents: read
      id-token: write
    name: Dev
    uses: ./.github/workflows/deploy-to-dev.yaml
    secrets:
      NAIS_DEPLOY_API_KEY: ${{ secrets.NAIS_DEPLOY_API_KEY }}
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

  deploy_to_prod:
    permissions:
      contents: read
      id-token: write
    name: Prod
    needs: deploy_to_dev
    uses: ./.github/workflows/deploy-to-prod.yaml
    secrets:
      NAIS_DEPLOY_API_KEY: ${{ secrets.NAIS_DEPLOY_API_KEY }}
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
